#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

####################
# links to add
panel_link("shellinabox", "manager");

# templates to expand
    templates2events("/etc/sysconfig/shellinaboxd", qw( conf-shellinaboxd  bootstrap-console-save console-save ));
    templates2events("/etc/httpd/shell-conf/httpd.conf", qw( conf-shellinaboxd  bootstrap-console-save console-save ));
    templates2events("/etc/httpd/conf/httpd.conf", qw( conf-shellinaboxd));


# services to launch on event
    safe_symlink("restart", "root/etc/e-smith/events/conf-shellinaboxd/services2adjust/shellinaboxd");
    safe_symlink("sigusr1", "root/etc/e-smith/events/conf-shellinaboxd/services2adjust/httpd-e-smith");
    safe_symlink("sigusr1", "root/etc/e-smith/events/conf-shellinaboxd/services2adjust/httpd-shell");

    safe_symlink("restart", "root/etc/e-smith/events/console-save/services2adjust/shellinaboxd");
    safe_symlink("sigusr1", "root/etc/e-smith/events/console-save/services2adjust/httpd-shell");


# links for rc.d from init.d
	service_link_enhanced("shellinaboxd", "S99", "7");
	service_link_enhanced("shellinaboxd", "K45", "6");
	service_link_enhanced("shellinaboxd", "K45", "0");
	service_link_enhanced("shellinaboxd", "K45", "1");

    service_link_enhanced("httpd-shell", "S86", "7");
    service_link_enhanced("httpd-shell", "K15", "6");
    service_link_enhanced("httpd-shell", "K15", "0");
    service_link_enhanced("httpd-shell", "K15", "1");
    safe_symlink("../daemontools" , 'root/etc/rc.d/init.d/supervise/httpd-shell');
    safe_symlink("/var/service/httpd-shell" , 'root/service/httpd-shell');
