#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

####################
# links to add

# templates to expand
    templates2events("/etc/sysconfig/shellinaboxd", qw( conf-shellinaboxd  bootstrap-console-save console-save ));


# services to launch on event
    safe_symlink("restart", "root/etc/e-smith/events/conf-shellinaboxd/services2adjust/shellinaboxd");
    safe_symlink("restart", "root/etc/e-smith/events/conf-shellinaboxd/services2adjust/httpd-e-smith");


# links for rc.d from init.d
	service_link_enhanced("shellinaboxd", "S99", "7");
	service_link_enhanced("shellinaboxd", "K45", "6");
	service_link_enhanced("shellinaboxd", "K45", "0");
	service_link_enhanced("shellinaboxd", "K45", "1");
