#!/bin/sh
#----------------------------------------------------------------------
# copyright (C) 1999-2004 Mitel Networks Corporation
#----------------------------------------------------------------------

config=/etc/httpd/shell-conf/httpd.conf

[ -e $config ] || exit 1

exec 2>&1
exec chpst -P /usr/sbin/httpd -f $config -D FOREGROUND

